services:
  auth_db:
    image: postgres:18-alpine
    container_name: auth-db
    restart: unless-stopped

    command: >
      postgres
      -c shared_buffers=${SHARED_BUFFERS}
      -c work_mem=${WORK_MEM}
      -c maintenance_work_mem=${MAINTENANCE_WORK_MEM}
      -c max_connections=${MAX_CONNECTIONS}
      -c listen_addresses=${LISTEN_ADDRESSES}

    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  pgdata:
  my_data:
